title: Wenqi ZHANG's HomePage
description: Vincent ZHANG's personal homepage and study notes.
author: Dr. Wenqi ZHANG
avatar: /Protrait.jpg
email: szhzhangwq@outlook.com
location: BeiJing, China
skin: Sunset

# Import the theme
# theme: jekyll-theme-hamilton #指定使用Hamilton主题

# 使用 jekyll-remote-theme 远程加载主题
remote_theme: ngzhio/jekyll-theme-hamilton # 这是 Hamilton 主题的 GitHub 仓库路径

plugins:
  - jekyll-remote-theme # 确保这个插件被启用
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
 # username: ngzhio
 # card: summary
logo: Protrait.jpg
social:
  name: Vincent ZHANG
  links:
    - https://orcid.org/0000-0001-8142-7791
    - https://scholar.google.com/citations?user=C6pQQsQAAAAJ&hl=en&oi=ao
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
